openapi: 3.0.0
info:
  title: Simple API
  description: Shizen
  contact:
    email: grpaulino8@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://localhost:8080
  description: Shizen Server
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /plants:
    get:
      description: Returns every plant in the database.
      operationId: get_all_plants
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plant'
                x-content-type: application/json
        "401":
          description: error
      x-openapi-router-controller: shizen.controllers.default_controller
  /plant:
    get:
      description: Returns info about a specific plant.
      operationId: get_plant
      parameters:
      - name: id
        in: query
        description: The plant ID
        required: true
        style: form
        explode: true
        schema:
          minimum: 1
          type: integer
      responses:
        "200":
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Plant'
                x-content-type: application/json
        "401":
          description: error
      x-openapi-router-controller: shizen.controllers.default_controller
components:
  schemas:
    Plant:
      required:
      - common_name
      - description
      - id
      - image_url
      - label_name
      - scientific_name
      type: object
      properties:
        id:
          type: integer
          format: id
          example: 1
        common_name:
          type: string
          example: Arvore
        scientific_name:
          type: string
          example: Avorus
        label_name:
          type: string
          example: arvore1
        description:
          type: string
          example: descricao
        image_url:
          type: string
          example: https://aa.com/adasda.jpg
      example:
        image_url: https://aa.com/adasda.jpg
        description: descricao
        scientific_name: Avorus
        id: 1
        common_name: Arvore
        label_name: arvore1

