export const IP_API = "http://192.168.0.81"
export const API = IP_API + ":8080/"
export const AUTH_LOGIN = IP_API + "/shizen/login.php"
export const AUTH_REG = IP_API + "/shizen/register.php"
export const PASS_RECOVER = IP_API + "/shizen/recover.php"